### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jordanform** [stevenroach7/3DScanr#1]
Hi:

I would love to try this project. However, there is an issue when I trying to compile. 
![image](https://user-images.githubusercontent.com/2987653/45139195-8d3ad080-b1e1-11e8-8524-22f907204d8c.png)
It seems like the libraries in the folder are missing, should I compile those on my own or do you have recommendation?

**Comment by stevenroach7** [comment]
The XCode project doesn't come with the libraries prebuilt but I added them in the PCL_Build_Artifacts folder to save the trouble of someone having to build them just to try the project. 

Did you try dragging the files in the PCL_Build_Artifacts folder into the Linked Frameworks and Libraries list as described in the README?

**Comment by jordanform** [comment]
Yup, I did. Thanks for the response.

**Comment by jordanform** [comment]
Hey, I brew install the relative libraries and remove unrelated library search path and all works. Thanks for the amazing project.
